[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
solc_version = "0.8.16"

remappings = [
'@ds-test=lib/ds-test/src/',
'@oz-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts/',
'@diamond=lib/diamond-2-hardhat/contracts/',
'@oz=lib/openzeppelin-contracts/contracts/'
]